[ids]
*

[settings]
overload_tap_timeout = 300

[main]
# Always
# enter = rightalt
capslock = overload(nav, esc)
rightalt = overload(alt, backspace)

# normal keyboard
leftcontrol = leftalt
leftalt = overload(control, enter)

#Razer
#leftcontrol = overload(control, enter)
#
[nav]
h = left
j = down
k = up
l = right
