[ids]
*

[settings]
overload_tap_timeout = 200

[main]
# Always for learning new thing
# enter = rightalt

# normal keyboard
#capslock = esc
#leftcontrol = leftalt
#leftalt = overload(control, enter)
#rightalt = backspace
#backspace = rightalt

# Razer
leftcontrol = overload(control, enter)
