[ids]
*

[settings]
overload_tap_timeout = 200

[main]
# Always
# enter = rightalt
capslock = esc
esc = overload(nav, esc)
rightalt = backspace
# normal keyboard
#leftcontrol = leftalt
#leftalt = overload(control, enter)

# Razer
leftcontrol = overload(control, enter)

[nav]
h = left
j = down
k = up
l = right
