return {
  "akinsho/bufferline.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  config = function()
    require("bufferline").setup({
      options = {
        mode = "tabs",
        modified_icon = "",
        separator_style = "none",
        show_buffer_close_icons = false,
        show_close_icon = false,
      },
      highlights = {
        background = { bg = 'none' },
        fill = { bg = 'none' },
        buffer_selected = { bg = 'none', fg = '#fabd2f', bold = true }, -- Gruvbox vàng
        buffer_visible = { bg = 'none', fg = '#a89984' }, -- Gruvbox nâu nhạt
        close_button = { bg = 'none' },
        close_button_selected = { bg = 'none' },
        close_button_visible = { bg = 'none' },
        duplicate = { bg = 'none' },
        duplicate_selected = { bg = 'none' },
        duplicate_visible = { bg = 'none' },
        error = { bg = 'none' },
        error_selected = { bg = 'none' },
        error_visible = { bg = 'none' },
        hint = { bg = 'none' },
        hint_selected = { bg = 'none' },
        hint_visible = { bg = 'none' },
        indicator_selected = { bg = 'none' },
        indicator_visible = { bg = 'none' },
        info = { bg = 'none' },
        info_selected = { bg = 'none' },
        info_visible = { bg = 'none' },
        modified = { bg = 'none' },
        modified_selected = { bg = 'none' },
        modified_visible = { bg = 'none' },
        numbers = { bg = 'none' },
        numbers_selected = { bg = 'none' },
        numbers_visible = { bg = 'none' },
        offset_separator = { bg = 'none' },
        pick = { bg = 'none' },
        pick_selected = { bg = 'none' },
        pick_visible = { bg = 'none' },
        separator = { bg = 'none' },
        separator_selected = { bg = 'none' },
        separator_visible = { bg = 'none' },
        tab = { bg = 'none' },
        tab_close = { bg = 'none' },
        tab_selected = { bg = 'none' },
        tab_separator = { bg = 'none' },
        tab_separator_selected = { bg = 'none' },
        trunc_marker = { bg = 'none' },
        warning = { bg = 'none' },
        warning_selected = { bg = 'none' },
        warning_visible = { bg = 'none' },
      }
    })
  end,
}

